/** @type {import('ts-jest').JestConfigWithTsJest} */
export default {
  preset: 'ts-jest',
  testEnvironment: 'node',
  testPathIgnorePatterns: [
    'app.ts',
    'Router',
    'Routers',
    'dist',
    'user.mongo.model.ts',
    'addictions.mongo.model.ts',
    'users.routers.ts',
    'generalAddictions.mongo.model.ts',
    'conditions.mongo.model.ts',
    'addictions.routers.ts',
    'conditions.routers.ts',
  ],
  resolver: 'jest-ts-webcompat-resolver',
  collectCoverageFrom: ['src/**/*.ts'],
  coveragePathIgnorePatterns: [
    'Router',
    'app.ts',
    'Routers',
    'index.ts',
    'app.ts',
    'users.routers.ts',
    'entities',
    'user.mongo.model.ts',
    'addictions.mongo.model.ts',
    'generalAddictions.mongo.model.ts',
    'conditions.mongo.model.ts',
    'addictions.routers.ts',
    'conditions.routers.ts',
  ],
};
